// All randomization data pools for the Skyrim Buildnator.
// Each entry: { name, description? }. Categories are consumed generically by app.js.

const BUILD_DATA = {
  race: [
    { name: "Nord", description: "Children of the Sky — resistant to frost, born to battle." },
    { name: "Imperial", description: "Diplomats and traders, with a knack for finding coin." },
    { name: "Breton", description: "Innate resistance to magic and a talent for conjuration." },
    { name: "Redguard", description: "The most naturally talented warriors in Tamriel." },
    { name: "Altmer", description: "High Elves — gifted in the arcane arts, extra magicka." },
    { name: "Bosmer", description: "Wood Elves — masters of bow and stealth." },
    { name: "Dunmer", description: "Dark Elves — fire-resistant, balanced in blade and spell." },
    { name: "Orsimer", description: "Orcs — fearsome berserkers and master smiths." },
    { name: "Argonian", description: "Lizard-folk — waterbreathing, disease-resistant, slippery." },
    { name: "Khajiit", description: "Feline nomads — night eyes and deadly claws." },
  ],

  archetype: [
    { name: "Warrior", description: "Steel, sweat, and glory. Solve problems with sharp objects." },
    { name: "Mage", description: "Why swing a sword when reality itself obeys you?" },
    { name: "Thief", description: "If it isn't nailed down, it's yours." },
    { name: "Battlemage", description: "Heavy armor in one hand, devastation in the other." },
    { name: "Spellsword", description: "A blade backed by spellcraft — versatile and deadly." },
    { name: "Nightblade", description: "Illusion magic and a dagger from the shadows." },
    { name: "Assassin", description: "One target, one strike, no witnesses." },
    { name: "Archer", description: "If they can see you, you're doing it wrong. Loose from afar." },
    { name: "Paladin", description: "A holy warrior — restoration magic, heavy armor, no mercy for the undead." },
    { name: "Necromancer", description: "Death is not the end — it's the recruitment process." },
    { name: "Barbarian", description: "No armor crafting, no finesse. Hit things until they stop moving." },
    { name: "Monk", description: "Fists, robes, and inner peace (delivered at high velocity)." },
    { name: "Witchhunter", description: "Crossbow or bow, alchemy, and a grudge against everything magical." },
    { name: "Bard", description: "Charm, speechcraft, illusion — talk your way through Skyrim." },
    { name: "Pilgrim", description: "A wanderer visiting every shrine, surviving on wit and faith." },
  ],

  skills: [
    { name: "One-Handed" }, { name: "Two-Handed" }, { name: "Archery" },
    { name: "Block" }, { name: "Smithing" }, { name: "Heavy Armor" },
    { name: "Light Armor" }, { name: "Pickpocket" }, { name: "Lockpicking" },
    { name: "Sneak" }, { name: "Alchemy" }, { name: "Speech" },
    { name: "Alteration" }, { name: "Conjuration" }, { name: "Destruction" },
    { name: "Illusion" }, { name: "Restoration" }, { name: "Enchanting" },
  ],

  standingStone: [
    { name: "The Warrior", description: "Combat skills improve 20% faster." },
    { name: "The Mage", description: "Magic skills improve 20% faster." },
    { name: "The Thief", description: "Stealth skills improve 20% faster." },
    { name: "The Lover", description: "All skills improve 15% faster." },
    { name: "The Lord", description: "+50 armor rating and 25% magic resistance." },
    { name: "The Lady", description: "Health and stamina regenerate 25% faster." },
    { name: "The Steed", description: "+100 carry weight, no armor speed penalty." },
    { name: "The Apprentice", description: "Double magicka regen — but double weakness to magic." },
    { name: "The Atronach", description: "+50 magicka, 50% spell absorption, no magicka regen." },
    { name: "The Ritual", description: "Once a day, raise all nearby corpses to fight for you." },
    { name: "The Serpent", description: "Once a day, paralyze and poison a target." },
    { name: "The Shadow", description: "Once a day, become invisible for 60 seconds." },
    { name: "The Tower", description: "Once a day, unlock any expert-or-lower lock." },
  ],

  combatStyle: [
    { name: "Sword & Shield", description: "The classic. Block, bash, stab, repeat." },
    { name: "Dual Wield", description: "Two weapons, zero defense, maximum carnage." },
    { name: "Two-Handed", description: "Big weapon. Big swings. Big problems for everyone else." },
    { name: "Archery", description: "Death from a distance — preferably while sneaking." },
    { name: "Destruction Magic", description: "Fire, frost, and shock until nothing moves." },
    { name: "Conjuration Summons", description: "Let your minions do the dirty work." },
    { name: "Unarmed", description: "Fists only. Khajiit claws optional but recommended." },
    { name: "Sneak Attacks", description: "30x dagger multipliers are a lifestyle." },
    { name: "Spell & Blade", description: "Weapon in one hand, spell in the other." },
    { name: "Shouts First", description: "FUS RO DAH is always the answer. Lead with the Voice." },
  ],

  armor: [
    { name: "Heavy Armor", description: "Walk slow, hit hard, fear nothing." },
    { name: "Light Armor", description: "Mobility and protection in balance." },
    { name: "Mage Robes", description: "Enchanted cloth — your magicka is your armor." },
    { name: "Clothes Only", description: "No armor at all. Fashion over function. Good luck." },
  ],

  weapon: [
    { name: "Sword", description: "Fast, reliable, classic." },
    { name: "War Axe", description: "Make them bleed." },
    { name: "Mace", description: "Armor means nothing to you." },
    { name: "Greatsword", description: "Elegant, enormous, exhausting." },
    { name: "Battleaxe", description: "For when subtlety is not on the menu." },
    { name: "Warhammer", description: "The biggest, slowest, most satisfying option." },
    { name: "Dagger", description: "Small blade, huge sneak multipliers." },
    { name: "Bow", description: "The ol' reliable of Skyrim." },
    { name: "Crossbow", description: "Slow to reload, brutal on impact (Dawnguard)." },
    { name: "Staff", description: "Channel destruction without lifting a spellbook." },
    { name: "Fists", description: "Weapons are a crutch." },
  ],

  magicSchools: [
    { name: "Destruction", description: "Flames, frostbite, sparks — applied liberally." },
    { name: "Conjuration", description: "Summon atronachs, raise the dead, bind weapons." },
    { name: "Illusion", description: "Fury, fear, calm, invisibility — the puppeteer's school." },
    { name: "Alteration", description: "Mage armor, paralysis, and bending the rules of reality." },
    { name: "Restoration", description: "Heal yourself, ward off spells, turn the undead." },
  ],

  faction: [
    { name: "The Companions", description: "Honor, glory, and a furry little secret in Jorrvaskr." },
    { name: "College of Winterhold", description: "Skyrim's last bastion of magical learning." },
    { name: "Thieves Guild", description: "Restore the Guild's former glory, one heist at a time." },
    { name: "Dark Brotherhood", description: "Hail Sithis. The contracts won't fulfill themselves." },
    { name: "Imperial Legion", description: "Unite Skyrim under the Empire's banner." },
    { name: "Stormcloaks", description: "Skyrim belongs to the Nords!" },
    { name: "Dawnguard", description: "Vampire hunters with very large crossbows." },
    { name: "Volkihar Vampires", description: "Embrace the night. Become the monster." },
    { name: "Bards College", description: "Poems, drums, flutes — and the occasional tomb raid." },
    { name: "None", description: "A lone wanderer. Factions are for people with friends." },
  ],

  deity: [
    { name: "Akatosh", description: "Dragon God of Time, chief of the Divines." },
    { name: "Talos", description: "Hero-god of mankind. Worship at your own risk." },
    { name: "Kynareth", description: "Goddess of the air, wind, and sky." },
    { name: "Mara", description: "Goddess of love and compassion." },
    { name: "Dibella", description: "Goddess of beauty and artistry." },
    { name: "Stendarr", description: "God of mercy and righteous might." },
    { name: "Zenithar", description: "God of work and commerce." },
    { name: "Julianos", description: "God of wisdom and logic." },
    { name: "Arkay", description: "God of the cycle of life and death." },
    { name: "Nocturnal", description: "Daedric Prince of night and luck — patron of thieves." },
    { name: "Meridia", description: "Daedric Prince of life — sworn enemy of the undead." },
    { name: "Hircine", description: "Daedric Prince of the Hunt — father of werebeasts." },
    { name: "Mephala", description: "Daedric Prince of plots, lies, and webs." },
  ],

  morality: [
    { name: "Saint", description: "Never steal, never kill innocents, help everyone in need." },
    { name: "Good", description: "Do the right thing — but coin is coin." },
    { name: "Neutral", description: "Look out for yourself. The war isn't your problem." },
    { name: "Selfish", description: "Steal when convenient, help only when it pays." },
    { name: "Evil", description: "Skyrim is prey. Take what you want, burn the rest." },
  ],

  roleplayRules: [
    { name: "No fast travel", description: "Walk, ride, or take the carriage everywhere." },
    { name: "Sleep every night", description: "Find a bed before midnight, every night." },
    { name: "Eat three meals a day", description: "Breakfast, lunch, dinner — no skipping." },
    { name: "Never steal", description: "Not even that sweetroll." },
    { name: "Loot everything", description: "If it has value, it goes in the bag. Yes, all of it." },
    { name: "No looting the dead", description: "Grave-robbing is beneath you." },
    { name: "Vegetarian", description: "No meat. Cabbage soup forever." },
    { name: "Always accept a bounty", description: "Never turn down honest mercenary work." },
    { name: "No crafting", description: "Buy or find your gear — no smithing, alchemy, or enchanting." },
    { name: "Crafted gear only", description: "Only use weapons and armor you made yourself." },
    { name: "Always travel with a follower", description: "Never adventure alone." },
    { name: "Never use carriages", description: "Your own two feet (or hooves) only." },
    { name: "Return home weekly", description: "Visit your home (or an inn you call home) every in-game week." },
    { name: "No killing animals", description: "Wildlife is sacred. Run from wolves if you must." },
    { name: "Speak to every priest", description: "Visit and pray at every shrine you encounter." },
  ],

  challenge: [
    { name: "Permadeath", description: "If you die, delete the save. Start over." },
    { name: "No HUD", description: "Disable the HUD. Navigate by landmarks and instinct." },
    { name: "No followers", description: "You walk alone. No companions, no pets." },
    { name: "No potions in combat", description: "Drink before the fight or not at all." },
    { name: "Legendary difficulty", description: "Maximum difficulty from level 1. Pain." },
    { name: "No healing magic", description: "Potions, food, and patience only." },
    { name: "Sell nothing", description: "Income from quest rewards and found coin only." },
    { name: "One life per hold", description: "Die in a hold, never return to it." },
    { name: "No sprinting", description: "Dignified walking pace at all times." },
    { name: "No challenge", description: "The Divines smile upon you. Just enjoy the ride." },
  ],
};
