// Derives the mod's data layer from the site's js/data.js and js/batch.js
// (single source of truth). Emits:
//   mod/generated/BLD_Data.psc  - Papyrus global functions with all pools,
//                                 constraints and form-id lookups
//   mod/generated/data.json     - menu option lists consumed by the esp generator
//
// "One of" lists are pipe-joined strings; BLD_Data.InList() matches them with
// StringUtil.Find (SKSE), so no nested arrays are needed in Papyrus.

const fs = require("fs");
const path = require("path");

const repo = path.join(__dirname, "..", "..");
const outDir = path.join(__dirname, "..", "generated");
fs.mkdirSync(outDir, { recursive: true });

// data.js / batch.js are browser globals; eval them in one function scope.
// batch.js needs DOM/app stubs for its trailing listener registration.
function loadGlobals() {
  const dataSrc = fs.readFileSync(path.join(repo, "js", "data.js"), "utf8");
  const batchSrc = fs.readFileSync(path.join(repo, "js", "batch.js"), "utf8");
  const stub = `
    const document = { getElementById: () => ({ addEventListener: () => {} }) };
    const state = {};
  `;
  return new Function(
    dataSrc + "\n" + stub + "\n" + batchSrc + "\nreturn { BUILD_DATA, CONSOLE_DATA, SKILL_LEVEL };"
  )();
}

const { BUILD_DATA: D, CONSOLE_DATA: C, SKILL_LEVEL } = loadGlobals();

// ---------- Papyrus emission helpers ----------

const esc = (s) => String(s).replace(/"/g, "'");
const pipe = (arr) => (arr || []).join("|");

function stringArrayFn(name, values) {
  const L = [`String[] Function ${name}() Global`];
  L.push(`    String[] a = new String[${values.length}]`);
  values.forEach((v, i) => L.push(`    a[${i}] = "${esc(v)}"`));
  L.push("    Return a", "EndFunction", "");
  return L;
}

function boolArrayFn(name, values) {
  const L = [`Bool[] Function ${name}() Global`];
  L.push(`    Bool[] a = new Bool[${values.length}]`);
  values.forEach((v, i) => { if (v) L.push(`    a[${i}] = True`); });
  L.push("    Return a", "EndFunction", "");
  return L;
}

// String -> string lookup as an if-chain.
function lookupFn(name, map, fallback) {
  const L = [`String Function ${name}(String aKey) Global`];
  for (const [k, v] of Object.entries(map)) {
    L.push(`    If aKey == "${esc(k)}"`, `        Return "${esc(v)}"`, "    EndIf");
  }
  L.push(`    Return "${esc(fallback || "")}"`, "EndFunction", "");
  return L;
}

// String -> Form lookup via Game.GetFormFromFile.
function formLookupFn(name, entries, fallback) {
  const L = [`Form Function ${name}(String aKey) Global`];
  for (const [k, id, plugin] of entries) {
    L.push(`    If aKey == "${esc(k)}"`,
      `        Return Game.GetFormFromFile(0x${id}, "${plugin}")`, "    EndIf");
  }
  if (fallback) {
    L.push(`    Return Game.GetFormFromFile(0x${fallback[0]}, "${fallback[1]}")`);
  } else {
    L.push("    Return None");
  }
  L.push("EndFunction", "");
  return L;
}

// Dawnguard items carry the site's 02 load-order prefix; strip it and route
// to the right plugin.
function itemRef(id) {
  if (id.startsWith("02")) return [("000000" + id.slice(2)).slice(-8), "Dawnguard.esm"];
  return [id, "Skyrim.esm"];
}

// ---------- Build the .psc ----------

const out = [
  "ScriptName BLD_Data Hidden",
  "{GENERATED by mod/tools/gen-data.js from js/data.js + js/batch.js - do not edit by hand.}",
  "",
  "; A pipe-list ('A|B|C') membership test. Empty list -> false.",
  "Bool Function InList(String asName, String asList) Global",
  "    If asList == \"\"",
  "        Return False",
  "    EndIf",
  "    Return StringUtil.Find(\"|\" + asList + \"|\", \"|\" + asName + \"|\") >= 0",
  "EndFunction",
  "",
];

// Simple pools
out.push(...stringArrayFn("RaceNames", D.race.map((r) => r.name)));
out.push(...stringArrayFn("StoneNames", D.standingStone.map((s) => s.name)));
out.push(...stringArrayFn("StoneDescs", D.standingStone.map((s) => s.description)));
out.push(...stringArrayFn("MoralityNames", D.morality.map((m) => m.name)));
out.push(...stringArrayFn("MoralityDescs", D.morality.map((m) => m.description)));
out.push(...stringArrayFn("SchoolNames", D.magicSchools.map((s) => s.name)));
out.push(...stringArrayFn("SkillNames", D.skills.map((s) => s.name)));
out.push(...stringArrayFn("MagicSkills", ["Alteration", "Conjuration", "Destruction", "Illusion", "Restoration", "Enchanting"]));

// Weapons
out.push(...stringArrayFn("WeaponNames", D.weapon.map((w) => w.name)));
out.push(...stringArrayFn("WeaponSkills", D.weapon.map((w) => w.skill || "")));

// Armor
out.push(...stringArrayFn("ArmorNames", D.armor.map((a) => a.name)));
out.push(...boolArrayFn("ArmorAnyMagic", D.armor.map((a) => (a.requires || {}).anyMagic)));
out.push(...stringArrayFn("ArmorWeaponSkillNot", D.armor.map((a) => pipe((a.requires || {}).weaponSkillNot))));

// Combat styles
const styleReq = (s) => s.requires || {};
out.push(...stringArrayFn("StyleNames", D.combatStyle.map((s) => s.name)));
out.push(...stringArrayFn("StyleDescs", D.combatStyle.map((s) => s.description)));
out.push(...stringArrayFn("StyleWeaponName", D.combatStyle.map((s) => styleReq(s).weaponName || "")));
out.push(...stringArrayFn("StyleWeaponSkill", D.combatStyle.map((s) => styleReq(s).weaponSkill || "")));
out.push(...stringArrayFn("StyleSkill", D.combatStyle.map((s) => styleReq(s).skill || "")));
out.push(...stringArrayFn("StyleExcludeSkills", D.combatStyle.map((s) => pipe(styleReq(s).excludeSkills))));
out.push(...stringArrayFn("StyleMagicSchool", D.combatStyle.map((s) => styleReq(s).magicSchool || "")));
out.push(...boolArrayFn("StyleAnyMagic", D.combatStyle.map((s) => styleReq(s).anyMagic)));
out.push(...boolArrayFn("StyleDragonborn", D.combatStyle.map((s) => styleReq(s).dragonborn)));

// Archetypes
const archReq = (a) => a.requires || {};
out.push(...stringArrayFn("ArchNames", D.archetype.map((a) => a.name)));
out.push(...stringArrayFn("ArchDescs", D.archetype.map((a) => a.description)));
out.push(...stringArrayFn("ArchWeaponName", D.archetype.map((a) => archReq(a).weaponName || "")));
out.push(...stringArrayFn("ArchWeaponSkillIn", D.archetype.map((a) => pipe(archReq(a).weaponSkillIn))));
out.push(...stringArrayFn("ArchSkillIn", D.archetype.map((a) => pipe(archReq(a).skillIn))));
out.push(...stringArrayFn("ArchMagicSchool", D.archetype.map((a) => archReq(a).magicSchool || "")));
out.push(...stringArrayFn("ArchMagicSchoolIn", D.archetype.map((a) => pipe(archReq(a).magicSchoolIn))));
out.push(...boolArrayFn("ArchAnyMagic", D.archetype.map((a) => archReq(a).anyMagic)));
out.push(...stringArrayFn("ArchArmorIn", D.archetype.map((a) => pipe(archReq(a).armorIn))));

// Deities / factions / afflictions
out.push(...stringArrayFn("DeityNames", D.deity.map((d) => d.name)));
out.push(...stringArrayFn("DeityDescs", D.deity.map((d) => d.description)));
out.push(...boolArrayFn("DeityDaedric", D.deity.map((d) => d.daedric)));
out.push(...stringArrayFn("FactionNames", D.faction.map((f) => f.name)));
out.push(...stringArrayFn("FactionDescs", D.faction.map((f) => f.description)));
out.push(...boolArrayFn("FactionDaedric", D.faction.map((f) => f.daedric)));
out.push(...lookupFn("FactionHint", C.factionHints, "You walk alone."));
out.push(...stringArrayFn("AfflictionNames", D.affliction.map((a) => a.name)));
out.push(...stringArrayFn("AfflictionDescs", D.affliction.map((a) => a.description)));
out.push(...boolArrayFn("AfflictionDaedric", D.affliction.map((a) => a.daedric)));
out.push(...stringArrayFn("AfflictionIncompatFactions", D.affliction.map((a) => pipe(a.incompatibleFactions))));

// Roleplay rules
out.push(...stringArrayFn("RuleNames", D.roleplayRules.map((r) => r.name)));
out.push(...stringArrayFn("RuleDescs", D.roleplayRules.map((r) => r.description)));
out.push(...boolArrayFn("RuleRequiresMagic", D.roleplayRules.map((r) => r.requiresMagic)));
out.push(...boolArrayFn("RuleRequiresNoMagic", D.roleplayRules.map((r) => r.requiresNoMagic)));
out.push(...boolArrayFn("RuleNoDaedra", D.roleplayRules.map((r) => r.noDaedra)));
out.push(...stringArrayFn("RuleIncompatWeapon", D.roleplayRules.map((r) => r.incompatibleWeapon || "")));
out.push(...stringArrayFn("RuleIncompatDeities", D.roleplayRules.map((r) => pipe(r.incompatibleDeities))));
out.push(...stringArrayFn("RuleIncompatFactions", D.roleplayRules.map((r) => pipe(r.incompatibleFactions))));

// Conflict groups (pipe-joined; two names conflict when both live in a group)
out.push(...stringArrayFn("SkillConflictGroups", D.skillConflicts.map(pipe)));
out.push(...stringArrayFn("RuleConflictGroups", D.ruleConflicts.map(pipe)));

// ---------- Name pools ----------
// PickName rolls gender-appropriate lore names for a race.
{
  const L = ["String Function PickName(String aRace, Bool abFemale) Global"];
  for (const [race, pools] of Object.entries(D.names)) {
    L.push(`    If aRace == "${esc(race)}"`);
    for (const g of ["female", "male"]) {
      const names = pools[g];
      L.push(`        ${g === "female" ? "If abFemale" : "Else"}`);
      L.push(`            String[] ${g[0]}${race} = new String[${names.length}]`);
      names.forEach((n, i) => L.push(`            ${g[0]}${race}[${i}] = "${esc(n)}"`));
      L.push(`            Return ${g[0]}${race}[Utility.RandomInt(0, ${names.length - 1})]`);
    }
    L.push("        EndIf", "    EndIf");
  }
  L.push('    Return "Adventurer"', "EndFunction", "");
  out.push(...L);
}

// ---------- Form-id lookups (from batch.js CONSOLE_DATA) ----------

out.push(`Int Function SkillLevel() Global`, `    Return ${SKILL_LEVEL}`, "EndFunction", "");
out.push(...lookupFn("SkillAv", C.skillAvs));
out.push(...formLookupFn("StoneAbility", Object.entries(C.stoneAbilities).map(([k, id]) => [k, ...itemRef(id)])));

// School spells: two per school, slot 0/1
{
  const L = ["Form Function SchoolSpell(String aSchool, Int aiSlot) Global"];
  for (const [school, spells] of Object.entries(C.schoolSpells)) {
    L.push(`    If aSchool == "${esc(school)}"`);
    spells.forEach(([name, id], i) => {
      const [fid, plugin] = itemRef(id);
      L.push(`        If aiSlot == ${i}`,
        `            Return Game.GetFormFromFile(0x${fid}, "${plugin}") ; ${name}`,
        "        EndIf");
    });
    L.push("    EndIf");
  }
  L.push("    Return None", "EndFunction", "");
  out.push(...L);
}

// Weapon items: main weapon + optional ammo
{
  const main = ["Form Function WeaponItem(String aWeapon) Global"];
  const ammo = ["Form Function WeaponAmmo(String aWeapon) Global"];
  const ammoCount = ["Int Function WeaponAmmoCount(String aWeapon) Global"];
  for (const [weapon, items] of Object.entries(C.weapons)) {
    const [w, a] = items;
    const [wid, wplug] = itemRef(w[1]);
    main.push(`    If aWeapon == "${esc(weapon)}"`,
      `        Return Game.GetFormFromFile(0x${wid}, "${wplug}") ; ${w[0]}`, "    EndIf");
    if (a) {
      const [aid, aplug] = itemRef(a[1]);
      ammo.push(`    If aWeapon == "${esc(weapon)}"`,
        `        Return Game.GetFormFromFile(0x${aid}, "${aplug}") ; ${a[0]}`, "    EndIf");
      ammoCount.push(`    If aWeapon == "${esc(weapon)}"`, `        Return ${a[2]}`, "    EndIf");
    }
  }
  main.push("    Return None", "EndFunction", "");
  ammo.push("    Return None", "EndFunction", "");
  ammoCount.push("    Return 0", "EndFunction", "");
  out.push(...main, ...ammo, ...ammoCount);
}

// Staves by school (default Staff of Magelight)
out.push(...formLookupFn("StaffForSchool",
  Object.entries(C.staffBySchool).map(([k, [, id]]) => [k, ...itemRef(id)]),
  itemRef(C.staffDefault[1])));

// Armor sets: up to 4 pieces, slot-indexed
{
  const L = ["Form Function ArmorPiece(String aArmor, Int aiSlot) Global"];
  for (const [armor, pieces] of Object.entries(C.armorSets)) {
    L.push(`    If aArmor == "${esc(armor)}"`);
    pieces.forEach(([name, id], i) => {
      const [fid, plugin] = itemRef(id);
      L.push(`        If aiSlot == ${i}`,
        `            Return Game.GetFormFromFile(0x${fid}, "${plugin}") ; ${name}`,
        "        EndIf");
    });
    L.push("    EndIf");
  }
  L.push("    Return None", "EndFunction", "");
  out.push(...L);
}

out.push(...formLookupFn("RobesForSchool",
  Object.entries(C.robesBySchool).map(([k, id]) => [k, ...itemRef(id)])));
out.push(...formLookupFn("ShieldForArmor",
  Object.entries(C.shields).filter(([k]) => k !== "default").map(([k, [, id]]) => [k, ...itemRef(id)]),
  itemRef(C.shields.default[1])));

fs.writeFileSync(path.join(outDir, "BLD_Data.psc"), out.join("\n") + "\n");

// ---------- data.json for the esp generator (menu option lists) ----------

const menus = {
  race: D.race.map((r) => r.name),
  archetype: D.archetype.map((a) => a.name),
  skills: D.skills.map((s) => s.name),
  standingStone: D.standingStone.map((s) => s.name),
  combatStyle: D.combatStyle.map((s) => s.name),
  armor: D.armor.map((a) => a.name),
  weapon: D.weapon.map((w) => w.name),
  magicSchools: D.magicSchools.map((s) => s.name),
  affliction: D.affliction.map((a) => a.name),
  faction: D.faction.map((f) => f.name),
  deity: D.deity.map((d) => d.name),
  morality: D.morality.map((m) => m.name),
  roleplayRules: D.roleplayRules.map((r) => r.name),
};

fs.writeFileSync(path.join(outDir, "data.json"), JSON.stringify({ menus }, null, 2) + "\n");

const counts = Object.entries(menus).map(([k, v]) => `${k}:${v.length}`).join(" ");
console.log(`gen-data OK â€” BLD_Data.psc + data.json (${counts})`);

